---
# ---------------------------
# Kalliope default settings
# Use YAML syntax
# ---------------------------

# ---------------------------
# Trigger
# ---------------------------
# This is the trigger that will catch your magic work to wake up Kalliope
default_trigger: "snowboy"

# Trigger engine configuration
# Available engine are:
# - snowboy
triggers:
  - snowboy:
      pmdl_file: "trigger/kalliope-ES.pmdl"


# ---------------------------
# Speech to text
# ---------------------------

# This is the STT that will be used by default
default_speech_to_text: "google"

# Speech to text options
#recognition_options:
#  energy_threshold: 4000
#  adjust_for_ambient_noise_second: 1

# Spreech to Text engines configuration
# Available engine are:
# - google (via SpeechRecognition)
# - wit
# - bing
# - apiai
# - houndify
# - cmusphinx (must be installed first)
speech_to_text:
  - google:
      language: "es-ES"

# ---------------------------
# Text to speech
# ---------------------------
# This is the default TTS that will be used by Kalliope to talk.
default_text_to_speech: "pico2wave"
# where we store generated audio files from TTS engine to reuse them
cache_path: "/tmp/kalliope_tts_cache"

# Text to Spreech engines configuration
# Available engine are:
# - pico2wave
# - watson
# - pico2wave
# - googletts
# - voicerss
text_to_speech:
  - pico2wave:
      language: "es-ES"
      cache: True
  - googletts:
      language: "es"
      cache: True
  - voicerss:
      language: "es-es"
      cache: True

# ---------------------------
# players
# ---------------------------
# This is the sound player that will be used by default
default_player: "mplayer"

# players configuration
# Available engine are:
# - mplayer
# - pyalsaaudio       # no mp3
# - pyaudioplayer     # no mp3
# - sounddeviceplayer # no mp3
players:
  - mplayer: {}
  - pyalsaaudio:
     device: "default"
     convert_to_wav: True
  - pyaudioplayer:
     convert_to_wav: True
  - sounddeviceplayer:
     convert_to_wav: True

# ---------------------------
# Hooks
# ---------------------------
hooks:
  on_start: "on-start-synapse"
  on_waiting_for_trigger:
  on_triggered: "on-triggered-synapse"
  on_start_listening:
  on_stop_listening:
  on_order_found:
  on_order_not_found: "order-not-found-synapse"
  on_mute:
  on_unmute:
  on_start_speaking:
  on_stop_speaking:

# ---------------------------
# Rest API
# ---------------------------
rest_api:
  active: True
  port: 5000
  password_protected: True
  login: admin
  password: secret
  allowed_cors_origin: "*"

# ---------------------------
# Default Synapse
# ---------------------------
# Specify an optional default synapse response in case your order is not found.
default_synapse: "default-synapse"

# ---------------------------
# resource directory path
# ---------------------------
resource_directory:
  neuron: "resources/neurons"
  stt: "resources/stt"
  tts: "resources/tts"
  signal: "resources/signal"
#  trigger: "resources/trigger"
#

# ---------------------------
# Global files variables
# /!\ If a variable is defined in different files, the last file defines the value.
# ---------------------------
var_files:
  - global_variables/variables.yml
#  - variables2.yml

# -------------
# Start options
# -------------
#start_options:
#  muted: False
